#ifndef VULKAN_CONVERSION_TYPES_H
#define VULKAN_CONVERSION_TYPES_H

#define VULKAN_CONVERSION_NONE   0
#define VULKAN_CONVERSION_LINEAR 1
#define VULKAN_CONVERSION_SRGB   2

#endif // VULKAN_CONVERSION_TYPES_H
